name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100' # SDK Version to use.
      - run: dotnet build --configuration Release

      - name: dotnet publish
        run: |
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/github 
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v1
        with: 
          app-name: GithubDotNetCore  # Replace with your app name
          publish-profile: ${{ secrets.azureWebAppPublishProfile }} 
          package: ${{env.DOTNET_ROOT}}/github 
